"""add color column to vehicles

Revision ID: 7b026a0ae207
Revises: 9849d3c773b6
Create Date: 2026-06-11 11:55:51.873877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b026a0ae207'
down_revision = '9849d3c773b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=True))
        batch_op.drop_constraint(batch_op.f('vehicles_plate_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))
        batch_op.create_unique_constraint(batch_op.f('vehicles_plate_number_key'), ['plate_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('color')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('reason')
        batch_op.drop_column('camera_id')

    # ### end Alembic commands ###
